=== yhae86/xiaoqi11/sheishiwodibot-master/src/main/resources/sheishiwodibot.dtd
<!ELEMENT sheishiwodibot (language+)>
<!ELEMENT language (strings,words)>
<!ELEMENT strings (string+)>
<!ELEMENT string (#PCDATA) >
<!ELEMENT words (word+)>
<!ELEMENT word (word1,word2)>
<!ELEMENT word1 (#PCDATA)>
<!ELEMENT word2 (#PCDATA)>

<!ATTLIST language language (en|zh_cn|zn|ja|hi-in|vi) #REQUIRED >
<!ATTLIST language alias CDATA #REQUIRED>
<!ATTLIST string name CDATA #REQUIRED >

=== yhae86/xiaoqi11/sheishiwodibot-master/src/main/resources/strings.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE sheishiwodibot SYSTEM "sheishiwodibot.dtd">
<sheishiwodibot>
    <language language="en" alias="English">
        <strings>
            <string name="PleaseSetLanguage">
                Please set language ^_^
            </string>
            <string name="languageSetFinish">
                The {user} sets the language to {alias}
            </string>
            <string name="help">
                <![CDATA[
            Use the command /newgame to create a game. After the game starts, everyone will get their own game words, and some players will get secret agent words. Every civilian needs to describe his words and prove that he is not an undercover agent, but do not let the undercover agent know his words. Those with secret agent words also need to prove that they are not undercover agents.
            Each round must have at least 60 seconds of voting time.
            When the number of civilians is the same as the number of undercover agents, the undercover agents win !
                ]]>
            </string>
            <string name="userCreateGame">
                {user} creates a new game
            </string>
            <string name="commandInGroup">
                Please use the command in the group ^_^
            </string>
            <string name="record">
                <![CDATA[
            Join the game: {joinGame} times
            Complete the game: {completeGame} times
            Quit the game: {exitGame} times
            Civilian role: {word_people} games
            Undercover role: {word_spy} games
            Civilian victories: {word_people_victory} games
            Undercover wins: {word_spy_victory} games
            Fraction: {fraction}
                ]]>
            </string>
            <string name="InTheGame">This group is in the game</string>
            <string name="joinGame">join game</string>
            <string name="GamePlayerWaiting">Undercover game waiting for players to enter, let's play together. Existing
                members:
            </string>
            <string name="ready">Ready</string>
            <string name="TimeoutShutdown">No operation for a long time, the game has been closed automatically!
            </string>
            <string name="sendWord"><![CDATA[Your game word in the {groupName} group is: <b>{word}</b>]]></string>
            <string name="exitGame">{user} has exited the game</string>
            <string name="speechTime">Next is the speech time. After {time} seconds, the {round} round of voting will
                begin.
            </string>
            <string name="ViewWord">view word</string>
            <string name="gameStart">All players are ready, the game starts</string>
            <string name="votingStart">Start voting now, who do you want to eliminate?</string>
            <string name="notVoteSelf">not vote self!</string>
            <string name="abstain">Abstainüè≥Ô∏è</string>
            <string name="success">success</string>
            <string name="failure">failure</string>
            <string name="abstained">{user} abstained</string>
            <string name="notVote">{user} did not vote within the specified time</string>
            <string name="votedTimeEnd">‚åõÔ∏èvoted time end:</string>
            <string name="everyoneVoted">‚úÖEveryone voted:</string>
            <string name="gameOver">GAME OVER</string>
            <string name="aboutToVoteL">Voting soon,</string>
            <string name="aboutToVoteR">Haven't spoken yet</string>
            <string name="notAdmin">[<![CDATA[
            <i>I didn‚Äôt see anyone talking, I might not have permission</i>
            ]]></string>
            <string name="userWordIs">{user}'s word is {word}</string>
            <string name="eliminatedInThisRound">Eliminated in this round:</string>
            <string name="gameSettlement">The game is being settled, please wait</string>
            <string name="remainingPersonnel">Remaining personnel ({remainingPeople}/{totalPeople}):</string>

        </strings>
        <words>
            <word>
                <word1>Valentine's Day</word1>
                <word2>Singles' Day</word2>
            </word>
            <word>
                <word1>The Ugly Duckling</word1>
                <word2>Cinderella</word2>
            </word>
            <word>
                <word1>Rich second generation</word1>
                <word2>tall and handsome</word2>
            </word>
            <word>
                <word1>Bubble gum</word1>
                <word2>lollipop</word2>
            </word>
            <word>
                <word1>Salted fish</word1>
                <word2>boiled fish</word2>
            </word>
            <word>
                <word1>Shampoo</word1>
                <word2>conditioner</word2>
            </word>
            <word>
                <word1>Roller coaster</word1>
                <word2>bumper car</word2>
            </word>
            <word>
                <word1>Fan</word1>
                <word2>air conditioner</word2>
            </word>
            <word>
                <word1>Biscuits</word1>
                <word2>potato chips</word2>
            </word>
            <word>
                <word1>Glass</word1>
                <word2>mirror</word2>
            </word>
            <word>
                <word1>Paper towels</word1>
                <word2>wet wipes</word2>
            </word>
            <word>
                <word1>Guitar</word1>
                <word2>lute</word2>
            </word>
            <word>
                <word1>Train</word1>
                <word2>subway</word2>
            </word>
            <word>
                <word1>Cabbage</word1>
                <word2>lettuce</word2>
            </word>
            <word>
                <word1>Dolphins</word1>
                <word2>sea lions</word2>
            </word>
            <word>
                <word1>Paper towels</word1>
                <word2>handkerchiefs</word2>
            </word>
            <word>
                <word1>Go forward courageously</word1>
                <word2>go all out</word2>
            </word>
            <word>
                <word1>Myopic mouse</word1>
                <word2>frog at the bottom of the well</word2>
            </word>
            <word>
                <word1>Champion</word1>
                <word2>first</word2>
            </word>
            <word>
                <word1>Lavender</word1>
                <word2>gypsophila.</word2>
            </word>
            <word>
                <word1>Donnie Yen</word1>
                <word2>Jet Li</word2>
            </word>
            <word>
                <word1>First of all</word1>
                <word2>ex-boyfriend</word2>
            </word>
            <word>
                <word1>Jackfruit</word1>
                <word2>durian</word2>
            </word>
            <word>
                <word1>Memphis</word1>
                <word2>Le Jia</word2>
            </word>
            <word>
                <word1>Myopic mouse</word1>
                <word2>frog at the bottom of the well</word2>
            </word>
            <word>
                <word1>Chewing gum</word1>
                <word2>xylitol</word2>
            </word>
            <word>
                <word1>Chili</word1>
                <word2>mustard sauce</word2>
            </word>
            <word>
                <word1>Rich second generation</word1>
                <word2>tall and handsome</word2>
            </word>
            <word>
                <word1>Morning light</word1>
                <word2>true color</word2>
            </word>
            <word>
                <word1>White rabbit</word1>
                <word2>golden monkey</word2>
            </word>
            <word>
                <word1>Bread</word1>
                <word2>cake</word2>
            </word>
            <word>
                <word1>Paper towels</word1>
                <word2>handkerchiefs</word2>
            </word>
            <word>
                <word1>Cabbage</word1>
                <word2>lettuce</word2>
            </word>
            <word>
                <word1>Washing powder</word1>
                <word2>soap powder</word2>
            </word>
            <word>
                <word1>Dong Yong</word1>
                <word2>Xu Xian</word2>
            </word>
            <word>
                <word1>Mobile phone</word1>
                <word2>landline</word2>
            </word>
            <word>
                <word1>The Ugly Duckling</word1>
                <word2>Cinderella</word2>
            </word>
            <word>
                <word1>Spiderman</word1>
                <word2>batman</word2>
            </word>
            <word>
                <word1>Dolphins</word1>
                <word2>sea lions</word2>
            </word>
            <word>
                <word1>Lie in ambush on all sides</word1>
                <word2>bewildered on all sides</word2>
            </word>
            <word>
                <word1>Guitar</word1>
                <word2>lute</word2>
            </word>
            <word>
                <word1>Composition</word1>
                <word2>essay</word2>
            </word>
            <word>
                <word1>The remaining girl</word1>
                <word2>sister royal</word2>
            </word>
            <word>
                <word1>Soy milk</word1>
                <word2>milk</word2>
            </word>
            <word>
                <word1>Animals</word1>
                <word2>plants</word2>
            </word>
            <word>
                <word1>Valentine's Day</word1>
                <word2>Singles' Day</word2>
            </word>
            <word>
                <word1>Bubble gum</word1>
                <word2>lollipop</word2>
            </word>
            <word>
